---
- name: Copy backend dist files to remote server
  become: true
  copy:
    src: /root/project/backend
    dest: ~/

- name: Executing node
  become: true
  shell: |
    pwd
    cd /root/backend
    npm i
    npm run build
    cd ..
    # Zip the directory
    tar -C backend -czvf artifact.tar.gz .
    cd backend
    pm2 stop default
    pm2 start npm -- run start
