---
- name: Copy backend dist files to remote server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend 
    npm install
    npm run build
    npm run prestart:prod
    pm2 stop default
    pm2 start npm -- start
