---
# - name: Copy backend dist files to remote server
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

- name: Executing node
  become: true
  shell: |
    cd backend
    npm i
    npm run build
    #cd /home/ubuntu/backend 
    #npm run prestart:prod
    cd ..
    # Zip the directory
    tar -C backend -czvf artifact.tar.gz .
    #cd .circleci/ansible
    cd backend
    pm2 stop default
    pm2 start npm -- start
