---
- name: Copy backend dist files to remote server
  become: yes
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: Executing node
  ansible.builtin.shell: |
    cd /home/ubuntu
    mkdir backend
    tar -vxf artifact.tar.gz -C backend
    rm -f artifact.tar.gz
    cd backend
    cp .env.sample .env
    npm install

- name: "run npm"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: /home/ubuntu/backend
