---
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend 
    npm install
    pm2 stop default
    pm2 start npm -- start
